// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGzWzODgStMjh1BCFUovdn6VjcexwFuLI',
    appId: '1:82576536500:web:ae375fe3c236acbf5278e1',
    messagingSenderId: '82576536500',
    projectId: 'fir-50a7f',
    authDomain: 'fir-50a7f.firebaseapp.com',
    databaseURL: 'https://fir-50a7f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-50a7f.appspot.com',
    measurementId: 'G-XW3W29940W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPUFk_ivFT7n7zzoiQiGKqkji9AFvH4k',
    appId: '1:82576536500:android:12b64eabdcc29e145278e1',
    messagingSenderId: '82576536500',
    projectId: 'fir-50a7f',
    databaseURL: 'https://fir-50a7f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-50a7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNa87fzjbwcZvxqOasr5WhuqVR_utygE',
    appId: '1:82576536500:ios:d9b50f4e7124fd1c5278e1',
    messagingSenderId: '82576536500',
    projectId: 'fir-50a7f',
    databaseURL: 'https://fir-50a7f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-50a7f.appspot.com',
    iosBundleId: 'com.mirjalol.localNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgNa87fzjbwcZvxqOasr5WhuqVR_utygE',
    appId: '1:82576536500:ios:bc8c8b6f636df8175278e1',
    messagingSenderId: '82576536500',
    projectId: 'fir-50a7f',
    databaseURL: 'https://fir-50a7f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-50a7f.appspot.com',
    iosBundleId: 'com.mirjalol.localNotification.RunnerTests',
  );
}
